name: build-test

env:
  DEPLOY_BRANCH_POSTFIX: deploy # Configure the destination branch postfix (code on "main" branch will be built and pushed into "main-POSTFIX" branch)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: "Build & Test"
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Install pytest and dependencies
        run: |
          pip install pytest

      - name: Run tests with pytest
        run: |
          python -m pytest

      # Build application into BUILD directory
      - name: Create BUILD directory and copy necessary application files
        run: |
          mkdir BUILD
          cp -r static BUILD/static  # copy the static directory and contents
          cp -r templates BUILD/templates  # copy the templates directory and contents
          cp -r app.py BUILD/app.py
          cp -r requirements.txt BUILD/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ./BUILD

  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "flask-tests"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D9B2040AA5D145AE8152346EB044CE27 }}
